#if !defined(AFX_GRPPMD_H__INCLUDED_)
#define AFX_GRPPMD_H__INCLUDED_
#ifdef  GRPPMD_EXPORTS
#define GRPPMD_API __declspec(dllexport)
#else
#define GRPPMD_API __declspec(dllimport)
#endif
	

/*BOOL GRPPMD_API Dispeditdialg(void *ep,HWND hWndParent);
BOOL GRPPMD_API Displistdialg(void *ep,HWND hWndParent);
BOOL GRPPMD_API Dispcombodialg(void *ep,HWND hWndParent);
BOOL GRPPMD_API Disptreedialg(void  *ep,HWND hWndParent);
BOOL GRPPMD_API Dispipadddialg(void *ep,HWND hWndParent);
BOOL GRPPMD_API Dispsliddialg(void  *ep,HWND hWndParent);
BOOL GRPPMD_API Dispprogressdialg(void *ep,HWND hWndParent);
BOOL GRPPMD_API Dispaboutdialg(HWND hWndParent);
BOOL GRPPMD_API Dispdatetimedialg(void *ep,HWND hWndParent);
BOOL GRPPMD_API Dispmonthcaldialg(void *ep,HWND hWndParent);
BOOL GRPPMD_API DispCheckdialg(void *ep,HWND hWndParent);*/
//BOOL GRPPMD_API DispTextdialg(char *str,int n,HWND hWndParent);
//BOOL GRPPMD_API DispScrTextdialg(char *str,int n,HWND hWndParent);
//BOOL GRPPMD_API DispFmtdialg(void *data,HWND hWndParent);
//BOOL GRPPMD_API DispPushdialg(void *push,HWND hWndParent);
//BOOL GRPPMD_API DispGetColorNum(BYTE*cr,HWND hWndParent);
//BOOL GRPPMD_API DispGetDllName(char *name,HWND hWndParent);
//BOOL GRPPMD_API DispGetPie(void *pa,HWND hWndParent);
//BOOL GRPPMD_API DispWebParm(void *pa,HWND hWndParent);
//BOOL GRPPMD_API DispScrollBar(void *pa,HWND hWndParent);




#endif